# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'DesignUp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!(false)
  use_modular_headers!

  pod 'FBAudienceNetwork'
  pod 'RealmSwift', '5.0.0-beta.1'
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'SDWebImage', '~> 5.0'
  pod 'JGProgressHUD'
  
end
